### ISSUE TITLE
Unknown vision tower

### ISSUE THREAD

**Issue by mcmayer** [XiaoduoAILab/XmodelVLM#2]
I tried to run `inference.py` (conda env set up as per the instructions), and somehow a full path expansion is stored as a hardcoded path,

`Unknown vision tower: /data2/xuwanting/LLaVA/llava/model/clip-vit-large-patch14-336/`

when `build_vision_tower` is called in `xmodelvlm/model/xmodelvlm.py`. 
I don't quite see where this path expansion is happening.

**Comment by harrytrolor** [comment]
You have to reset the vision_tower path to your chosen vision encoder  in the config.json file you downloaded from huggingface.

**Comment by New-Star-HLP** [comment]
Thanks to @harrytrolor , you need to download the vision encoder you want and change the relevant configuration file @mcmayer
