### ISSUE TITLE
about XDP projector 

### ISSUE THREAD

**Issue by JXXXX001** [XiaoduoAILab/XmodelVLM#3]
Can pretrained XDP models be provided？

**Comment by New-Star-HLP** [comment]
Well, we have provided the trained weights of the model on the [hugging face](https://huggingface.co/XiaoduoAILab/Xmodel_VLM/tree/main)。And the code of the XDP model is [here](https://github.com/XiaoduoAILab/XmodelVLM/blob/main/xmodelvlm/model/vision_projector.py)
