### ISSUE TITLE
Unknown vision tower  - Plz Improve/Correct Documentation

### ISSUE THREAD

**Issue by fahdmirza** [XiaoduoAILab/XmodelVLM#4]
Hello,
 Please improve the documentation in ReadMe if you want people to use your model. Clearly list how to and which vision encoder and which projector to download with complete command. I have wasted 4 hours trying to run both text and vision model and they are infested with errors. Even after downloading CLIP encoder, your script doesn't work:

``(xmodelvlm) Ubuntu@0055-kci-prxmx10068:~/XmodelVLM$ python3 inference.py
/home/Ubuntu/anaconda3/envs/xmodelvlm/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Traceback (most recent call last):
  File "/home/Ubuntu/XmodelVLM/inference.py", line 79, in <module>
    inference_once(args)
  File "/home/Ubuntu/XmodelVLM/inference.py", line 19, in inference_once
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.load_8bit, args.load_4bit)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/XmodelVLM/xmodelvlm/model/xmodelvlm.py", line 306, in load_pretrained_model
    model = XmodelLMForCausalLM.from_pretrained(model_path, trust_remote_code=True, low_cpu_mem_usage=True, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/anaconda3/envs/xmodelvlm/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3594, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/XmodelVLM/xmodelvlm/model/xmodel_lm.py", line 29, in __init__
    self.model = XmodelLMModel(config)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/XmodelVLM/xmodelvlm/model/xmodel_lm.py", line 21, in __init__
    super(XmodelLMModel, self).__init__(config)
  File "/home/Ubuntu/XmodelVLM/xmodelvlm/model/xmodelvlm.py", line 17, in __init__
    self.vision_tower = build_vision_tower(config, delay_load=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Ubuntu/XmodelVLM/xmodelvlm/model/vision_encoder.py", line 273, in build_vision_tower
    raise ValueError(f'Unknown vision tower: {vision_tower}')
ValueError: Unknown vision tower: /data1/xuwanting/LLaVA/llava/model/clip-vit-large-patch14-336/
(xmodelvlm) Ubuntu@0055-kci-prxmx10068:~/XmodelVLM$

**Comment by New-Star-HLP** [comment]
You need to modify the path of 'mm_vision_tower' in the config.json file.
**Tip**:  Please make sure that you are using the latest code and related virtual environments. (Include [checkpoint](https://huggingface.co/XiaoduoAILab/Xmodel_VLM), [vision encoder](https://huggingface.co/openai/clip-vit-large-patch14-336) and relevant file path in [config.json](https://huggingface.co/XiaoduoAILab/Xmodel_VLM/blob/main/config.json))
